version: '3'

services:
  app:
    build: ./docker/app
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached

  web:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sample-db
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - laravel-db-data:/var/lib/mysql

volumes:
  laravel-db-data:
    driver: local
